### ISSUE TITLE
/bin/bash: Argument list too long

### ISSUE THREAD

**Issue by akhiljalagam** [cdown/sshrc#2]
what should be the maximum size of sshrc files?

**Comment by cdown** [comment]
sshrc applies a [somewhat arbitrary limit](https://github.com/cdown/sshrc/blob/master/sshrc#L10), but it won't be enough in all cases, since it depends on the stack size and other factors.

**Comment by akhiljalagam** [comment]
yes. bash has a limit on arg size.  
workaround using cat  
`cat $sshrc_file | ssh "$DOMAIN" $SSHARGS "cat > $REMOTE_SSHRC_PATH"`  
and then load file.
